version: '3.8'
services:
    app:
        image: node:18
        volumes:
            - .:${PWD}
        working_dir: ${PWD}
        command: sh -c "corepack enable && pnpm install --frozen-lockfile && pnpm run dev"
        ports:
            - 3000:3000
